c_compiler:  # [linux]
  - gcc  # [linux]
c_compiler:  # [osx]
  - clang  # [osx]
c_compiler_version:  # [linux]
  - 13  # [linux]
c_compiler_version:  # [osx]
  - 17  # [osx]
c_stdlib_version:  # [osx]
  - 10.15  # [osx]
MACOSX_SDK_VERSION:  # [osx]
  - 10.15  # [osx]
