{% set name = "helm-ls" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mrjosh/helm-ls/archive/v{{ version }}.tar.gz
  sha256: 6cbbe74114e6a4b8cd0821e372190f67743bb0528ea364a969524c754ba00c22

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('go-cgo') }}
    - go-licenses

test:
  commands:
    - helm-ls --help

about:
  home: https://github.com/mrjosh/helm-ls
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Language server for Helm
  dev_url: https://github.com/mrjosh/helm-ls

extra:
  recipe-maintainers:
    - danielnachun
