{% set name = "helm-ls" %}
{% set version = "0.0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mrjosh/helm-ls/archive/v{{ version }}.tar.gz
  sha256: 8602139460f387eb2b423d15f1ade0eba67835dec6cdb73c9d9a13964e44a671

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('go-cgo') }}
    - go-licenses

test:
  commands:
    - helm-ls --help

about:
  home: https://github.com/mrjosh/helm-ls
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Language server for Helm
  dev_url: https://github.com/mrjosh/helm-ls

extra:
  recipe-maintainers:
    - danielnachun
