context:
  version: "0.1.1"

package:
  name: helm-ls
  version: ${{ version }}

source:
  url: https://github.com/mrjosh/helm-ls/archive/v${{ version }}.tar.gz
  sha256: f0db0f52c40d18dc18151f8df98c26afb7c1081b5fcf8d8e20c9094e1d3eb369

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('go-cgo') }}
    - go-licenses

tests:
  - script:
      - helm-ls --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Language server for Helm
  homepage: https://github.com/mrjosh/helm-ls
  repository: https://github.com/mrjosh/helm-ls

extra:
  recipe-maintainers:
    - danielnachun
